### ISSUE TITLE
Unable to parse git log when multiple quotes are present

### ISSUE THREAD

**Issue by maheshkkolla** [bookchin/gitty#62]
If the commit message is like this ` Revert "Revert "Fixing UI test"" ` then ` logSync() ` is not able to parse the logs and throws the following error: 
```
SyntaxError: Unexpected token R
    at Object.parse (native)
    at Object.module.exports.log (/Users/user/Projects/MyProject/node_modules/gitty/lib/parser.js:31:15)
    at Repository.logSync (/Users/user/Projects/MyProject/node_modules/gitty/lib/repository.js:116:16)
    at Object.module.exports.getRepoLogs (/Users/user/Projects/MyProject/modules/file1.js:21:21)
    at /Users/user/Projects/MyProject/routes/file2.js:23:18
    at Layer.handle [as handle_request] (/Users/user/Projects/MyProject/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/user/Projects/MyProject/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/user/Projects/MyProject/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/user/Projects/MyProject/node_modules/express/lib/router/layer.js:95:5)
```

Can you please look into the issue and help me to solve this problem.

**Comment by bookchin** [comment]
This should be taken care of here: https://github.com/bookchin/gitty/blob/master/lib/parser.js#L18

Are you using the latest version?

**Comment by maheshkkolla** [comment]
I am using version 3.3.6.

**Comment by bookchin** [comment]
Okay looks like a bug. I won't have time to look into it in the near term, but that function referenced above is where this is failing. I'd happily accept a PR in the meantime.

**Comment by sinchang** [comment]
```
{"commit":"23a20ce09db01e8a37a26e4f3355b7779e7191b6","author":"YOU <stackexchange.you@gmail.com>","date":"Sun Mar 5 00:40:14 2017 +0000","message":"chore: \s match all whitespaces (#5091)"},
                                                                                                                                                            ^
SyntaxError: Unexpected token s in JSON at position 148448
```
throw error when commit message contains '\s'
